### PR TITLE
Switch to requests module instead of httplib2

### PR DESCRIPTION
**Pull request by grodzik**
Httplibs2 has limited support for proxy via some external package
SocksiPy, which is even hard to get from PyPi. Also it seems broken
on Python3 (tested with Python 3.4)

Requests on the other hand support proxies out of the box.

### CODE REVIEW

**Comment by lwahlmeier** [comment]
Honestly I have never really liked the requests at all, and avoid it as much as I can.  I have also been wanting to change out httplib2 with something more async basically allowing parallel downloads.  I you really need/want this change for the proxy I can go ahead and bring it in, but it might change again later.

**Comment by grodzik** [comment]
I'm not bound to requests, so I don't care if there will be something else later on, but I do need working proxy since I need to sync corporate laptop.

As a side question, any particular reasons to dislike requests?

**Comment by lwahlmeier** [comment]
I will keep that in mind for when/if I move to an async library.  I will probably take a day or 2 on this pr to test it out and make sure my stuff is still all working, but assuming no issues i think its good.

Honestly just really dont like their api, but to be fair the httpclient api can get hairy pretty fast so most libraries are pretty bad, and there is probably not one good solution either.  I tend to like very low level api's esp for networking and protocols.

**Comment by lwahlmeier** [comment]
Sorry it took me so long to get to look at this, everything seems to be working good for my setup.

**Pull request merged**
