### PR TITLE
PEP8 compilant and fetch password from external command

### PR DESCRIPTION
**Pull request by grodzik**
Hi,

Don't know if you accept merge request or not, but here are my two cents.
First commit makes code more PEP8 compilant, there are few left, but that's minimal.
Second one adds new argument to use external command for obtaining password.
A common scenario is to use Password Store (or other similar tool) to keep your passwords under GPG encrypted files, and instead of typing password in prompt, ownSync can use external command for that. This also enables use of this tool in cron for example.

### CODE REVIEW

**Comment by lwahlmeier** [comment]
@grodzik I am definitely all for accepting pull requests.  And I think there are some great changes in here I would love to include.  The only issue is doing strict PEP-8 compliance, imo its more just suggestions then anything else.  I personally feel that its very outdated, esp things like the 72char line limit, 120 is more sane.  I also much prefer the 2 spaces to 4 per indent and would prefer to keep this project that way.

I would prefer if you could move the 4 spaces back to 2 and change the line wrapping back to 120.   Should probably also move it to the next version (0.7.0).   If you dont have the time I can go ahead and merge then do it myself if you prefer.

**Comment by grodzik** [comment]
Cool, I'll rollback spaces and line length then. I'll try to do this today in the evening.

**Comment by grodzik** [comment]
Reverted the changes. As for 0.7.0 you may want to wait a bit for next PR of mine with `--exlude` option

**Comment by lwahlmeier** [comment]
yeah we can wait if you want to add more features first.  Also it looks like ownSyncUtils.py is still at 4 spaces.  I can change it back after the merge if you want.

**Comment by grodzik** [comment]
Arghh... Just forgot to run `git add` on that file, after I switched to 2 spaces ;)

**Comment by lwahlmeier** [comment]
awesome, looks great, thanks

**Pull request merged**
